site_name: IACS URI Platform User Manual V1.0
site_description: Official documentation for the Unified Requirement Implementation (URI) Platform.
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - content.tabs.link
    - content.code.copy
  palette:
    # Palette toggle for Light Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for Dark Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  favicon: assets/favicon.ico

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - "1. Introduction": index.md
  - "2. Access and Login": access.md
  - "3. Query UR Status": query.md
  - "4. Update URI Status": update.md
  - "5. Report Printing": reporting.md
  - "Annex: Process Flowchart": annex.md


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde